void ppttx20_particles(int i_a, observable_set & oset);

void ppttx20_cuts(int i_a, observable_set & oset);
void ppttx20_cuts_test(int i_a, observable_set & oset);

void ppttx20_moments(observable_set & oset);

void ppttx20_calculate_dynamic_scale(int i_a, observable_set & oset);
void ppttx20_calculate_dynamic_scale_RA(int i_a, observable_set & oset);
void ppttx20_calculate_dynamic_scale_TSV(int i_a, observable_set & oset);

void ppttx20_optimize_minv_born(phasespace_set & psi);
int ppttx20_determination_MCchannels_born(int no_ps, phasespace_set & psi);
void ppttx20_ac_tau_psp_born(int no_ps, vector<int> & tau_MC_map, phasespace_set & psi);
void ppttx20_ag_psp_born(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_born(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_born(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ax_psp_200_gg_ttx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_200_gg_ttx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_200_gg_ttx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_200_ddx_ttx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_200_ddx_ttx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_200_ddx_ttx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_200_uux_ttx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_200_uux_ttx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_200_uux_ttx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_200_bbx_ttx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_200_bbx_ttx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_200_bbx_ttx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_phasespacepoint_born(observable_set & oset);

void ppttx20_phasespacepoint_collinear(observable_set & oset);

void ppttx20_optimize_minv_real(phasespace_set & psi);
int ppttx20_determination_MCchannels_real(int no_ps, phasespace_set & psi);
void ppttx20_ac_tau_psp_real(int no_ps, vector<int> & tau_MC_map, phasespace_set & psi);
void ppttx20_ag_psp_real(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_real(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_real(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ax_psp_300_gg_ttxg(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_300_gg_ttxg(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_300_gg_ttxg(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_300_gd_ttxd(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_300_gd_ttxd(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_300_gd_ttxd(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_300_gu_ttxu(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_300_gu_ttxu(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_300_gu_ttxu(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_300_gb_ttxb(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_300_gb_ttxb(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_300_gb_ttxb(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_300_gdx_ttxdx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_300_gdx_ttxdx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_300_gdx_ttxdx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_300_gux_ttxux(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_300_gux_ttxux(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_300_gux_ttxux(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_300_gbx_ttxbx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_300_gbx_ttxbx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_300_gbx_ttxbx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_300_ddx_ttxg(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_300_ddx_ttxg(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_300_ddx_ttxg(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_300_uux_ttxg(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_300_uux_ttxg(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_300_uux_ttxg(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_300_bbx_ttxg(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_300_bbx_ttxg(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_300_bbx_ttxg(int no_ps, int zero, phasespace_set & psi);
void ppttx20_phasespacepoint_real(observable_set & oset);

void ppttx20_phasespacepoint_realcollinear(observable_set & oset);

void ppttx20_optimize_minv_doublereal(phasespace_set & psi);
int ppttx20_determination_MCchannels_doublereal(int no_ps, phasespace_set & psi);
void ppttx20_ac_tau_psp_doublereal(int no_ps, vector<int> & tau_MC_map, phasespace_set & psi);
void ppttx20_ag_psp_doublereal(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_doublereal(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_doublereal(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ax_psp_400_gg_ttxgg(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_gg_ttxgg(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_gg_ttxgg(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_gg_ttxddx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_gg_ttxddx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_gg_ttxddx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_gg_ttxuux(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_gg_ttxuux(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_gg_ttxuux(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_gg_ttxbbx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_gg_ttxbbx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_gg_ttxbbx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_gd_ttxgd(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_gd_ttxgd(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_gd_ttxgd(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_gu_ttxgu(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_gu_ttxgu(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_gu_ttxgu(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_gb_ttxgb(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_gb_ttxgb(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_gb_ttxgb(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_gdx_ttxgdx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_gdx_ttxgdx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_gdx_ttxgdx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_gux_ttxgux(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_gux_ttxgux(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_gux_ttxgux(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_gbx_ttxgbx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_gbx_ttxgbx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_gbx_ttxgbx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_dd_ttxdd(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_dd_ttxdd(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_dd_ttxdd(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_du_ttxdu(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_du_ttxdu(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_du_ttxdu(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_ds_ttxds(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_ds_ttxds(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_ds_ttxds(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_dc_ttxdc(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_dc_ttxdc(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_dc_ttxdc(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_db_ttxdb(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_db_ttxdb(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_db_ttxdb(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_ddx_ttxgg(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_ddx_ttxgg(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_ddx_ttxgg(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_ddx_ttxddx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_ddx_ttxddx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_ddx_ttxddx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_ddx_ttxuux(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_ddx_ttxuux(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_ddx_ttxuux(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_ddx_ttxssx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_ddx_ttxssx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_ddx_ttxssx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_ddx_ttxccx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_ddx_ttxccx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_ddx_ttxccx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_ddx_ttxbbx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_ddx_ttxbbx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_ddx_ttxbbx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_dux_ttxdux(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_dux_ttxdux(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_dux_ttxdux(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_dsx_ttxdsx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_dsx_ttxdsx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_dsx_ttxdsx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_dcx_ttxdcx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_dcx_ttxdcx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_dcx_ttxdcx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_dbx_ttxdbx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_dbx_ttxdbx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_dbx_ttxdbx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_uu_ttxuu(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_uu_ttxuu(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_uu_ttxuu(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_uc_ttxuc(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_uc_ttxuc(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_uc_ttxuc(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_ub_ttxub(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_ub_ttxub(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_ub_ttxub(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_udx_ttxudx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_udx_ttxudx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_udx_ttxudx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_uux_ttxgg(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_uux_ttxgg(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_uux_ttxgg(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_uux_ttxddx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_uux_ttxddx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_uux_ttxddx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_uux_ttxuux(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_uux_ttxuux(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_uux_ttxuux(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_uux_ttxssx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_uux_ttxssx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_uux_ttxssx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_uux_ttxccx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_uux_ttxccx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_uux_ttxccx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_uux_ttxbbx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_uux_ttxbbx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_uux_ttxbbx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_usx_ttxusx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_usx_ttxusx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_usx_ttxusx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_ucx_ttxucx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_ucx_ttxucx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_ucx_ttxucx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_ubx_ttxubx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_ubx_ttxubx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_ubx_ttxubx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_bb_ttxbb(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_bb_ttxbb(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_bb_ttxbb(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_bdx_ttxbdx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_bdx_ttxbdx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_bdx_ttxbdx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_bux_ttxbux(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_bux_ttxbux(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_bux_ttxbux(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_bbx_ttxgg(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_bbx_ttxgg(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_bbx_ttxgg(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_bbx_ttxddx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_bbx_ttxddx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_bbx_ttxddx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_bbx_ttxuux(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_bbx_ttxuux(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_bbx_ttxuux(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_bbx_ttxbbx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_bbx_ttxbbx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_bbx_ttxbbx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_dxdx_ttxdxdx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_dxdx_ttxdxdx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_dxdx_ttxdxdx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_dxux_ttxdxux(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_dxux_ttxdxux(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_dxux_ttxdxux(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_dxsx_ttxdxsx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_dxsx_ttxdxsx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_dxsx_ttxdxsx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_dxcx_ttxdxcx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_dxcx_ttxdxcx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_dxcx_ttxdxcx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_dxbx_ttxdxbx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_dxbx_ttxdxbx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_dxbx_ttxdxbx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_uxux_ttxuxux(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_uxux_ttxuxux(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_uxux_ttxuxux(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_uxcx_ttxuxcx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_uxcx_ttxuxcx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_uxcx_ttxuxcx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_uxbx_ttxuxbx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_uxbx_ttxuxbx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_uxbx_ttxuxbx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_ax_psp_400_bxbx_ttxbxbx(int no_ps, phasespace_set & psi);
void ppttx20_ac_psp_400_bxbx_ttxbxbx(int no_ps, int channel, phasespace_set & psi);
void ppttx20_ag_psp_400_bxbx_ttxbxbx(int no_ps, int zero, phasespace_set & psi);
void ppttx20_phasespacepoint_doublereal(observable_set & oset);

