universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Reduced_JES.C(\"TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc21Down.root\",\"TTTo2L2Nu\",\"boostedShiftedSrc21Down\",\"2016_postVFP\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_postVFP/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc21Down.root
error = HistoReduced_1000_TTTo2L2Nu_boostedShiftedSrc21Down.err
output = HistoReduced_1000_TTTo2L2Nu_boostedShiftedSrc21Down.out
log = HistoReduced_1000_TTTo2L2Nu_boostedShiftedSrc21Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_1000_TTTo2L2Nu_boostedShiftedSrc21Down.root
queue
