universe = vanilla
executable = submit_.sh
arguments = -l -b -q ResponseMatrices_JES.C(\"TTToHadronic_mtop178p5_TuneCP5_13TeV-powheg-pythia8.root\",\"TTToHadronic\",\"13TeV-powheg-pythia8\",\"2016_postVFP\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_postVFP/TTToHadronic_mtop178p5_TuneCP5_13TeV-powheg-pythia8.root
error = ResponsesEfficiency_TTToHadronic_13TeV-powheg-pythia8.err
output = ResponsesEfficiency_TTToHadronic_13TeV-powheg-pythia8.out
log = ResponsesEfficiency_TTToHadronic_13TeV-powheg-pythia8.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = ResponseMatrices_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = ResponsesEfficiency_TTToHadronic_13TeV-powheg-pythia8.root
queue
