// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/Users/georgebakas/Documents/HEP-NTUA_ul/VariationHandling/./FinalResults.cxx";

#endif
