universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Extended_JES.C(\"TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc24Down.root\",\"TTToHadronic\",\"boostedShiftedSrc24Down\",\"2016_preVFP\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_preVFP/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc24Down.root
error = HistoReduced_1000_TTToHadronic_boostedShiftedSrc24Down.err
output = HistoReduced_1000_TTToHadronic_boostedShiftedSrc24Down.out
log = HistoReduced_1000_TTToHadronic_boostedShiftedSrc24Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_1000_TTToHadronic_boostedShiftedSrc24Down.root
queue
