universe = vanilla
executable = submit_.sh
arguments = -l -b -q ResponseMatrices_JES.C(\"TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc18Up.root\",\"TTTo2L2Nu\",\"boostedShiftedSrc18Up\",\"2016_preVFP\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_preVFP/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc18Up.root
error = ResponsesEfficiency_TTTo2L2Nu_boostedShiftedSrc18Up.err
output = ResponsesEfficiency_TTTo2L2Nu_boostedShiftedSrc18Up.out
log = ResponsesEfficiency_TTTo2L2Nu_boostedShiftedSrc18Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = ResponseMatrices_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = ResponsesEfficiency_TTTo2L2Nu_boostedShiftedSrc18Up.root
queue
