universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Extended_JES.C(\"TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc10Up.root\",\"TTTo2L2Nu\",\"boostedShiftedSrc10Up\",\"2017\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2017/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc10Up.root
error = Histo_1000_TTTo2L2Nu_boostedShiftedSrc10Up.err
output = Histo_1000_TTTo2L2Nu_boostedShiftedSrc10Up.out
log = Histo_1000_TTTo2L2Nu_boostedShiftedSrc10Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Extended_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = Histo_1000_TTTo2L2Nu_boostedShiftedSrc10Up.root
queue
