universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Extended_JES.C(\"TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc24Up.root\",\"TTToHadronic\",\"boostedShiftedSrc24Up\",\"2016_postVFP\",1200) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_postVFP/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc24Up.root
error = Histo_1200_TTToHadronic_boostedShiftedSrc24Up.err
output = Histo_1200_TTToHadronic_boostedShiftedSrc24Up.out
log = Histo_1200_TTToHadronic_boostedShiftedSrc24Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Extended_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = Histo_1200_TTToHadronic_boostedShiftedSrc24Up.root
queue
