universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Reduced_JES.C(\"TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc20Down.root\",\"TTToSemiLeptonic\",\"boostedShiftedSrc20Down\",\"2017\",1800) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2017/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc20Down.root
error = HistoReduced_1800_TTToSemiLeptonic_boostedShiftedSrc20Down.err
output = HistoReduced_1800_TTToSemiLeptonic_boostedShiftedSrc20Down.out
log = HistoReduced_1800_TTToSemiLeptonic_boostedShiftedSrc20Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_1800_TTToSemiLeptonic_boostedShiftedSrc20Down.root
queue
