universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Reduced_JES.C(\"TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc24Up.root\",\"TTTo2L2Nu\",\"boostedShiftedSrc24Up\",\"2017\",1400) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2017/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc24Up.root
error = HistoReduced_1400_TTTo2L2Nu_boostedShiftedSrc24Up.err
output = HistoReduced_1400_TTTo2L2Nu_boostedShiftedSrc24Up.out
log = HistoReduced_1400_TTTo2L2Nu_boostedShiftedSrc24Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_1400_TTTo2L2Nu_boostedShiftedSrc24Up.root
queue
