universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Extended_JES.C(\"TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc3Up.root\",\"TTToSemiLeptonic\",\"boostedShiftedSrc3Up\",\"2016_postVFP\",2000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_postVFP/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc3Up.root
error = Histo_2000_TTToSemiLeptonic_boostedShiftedSrc3Up.err
output = Histo_2000_TTToSemiLeptonic_boostedShiftedSrc3Up.out
log = Histo_2000_TTToSemiLeptonic_boostedShiftedSrc3Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Extended_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = Histo_2000_TTToSemiLeptonic_boostedShiftedSrc3Up.root
queue
