universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Extended_JES.C(\"TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc12Up.root\",\"TTToSemiLeptonic\",\"boostedShiftedSrc12Up\",\"2016_preVFP\",2000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_preVFP/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc12Up.root
error = Histo_2000_TTToSemiLeptonic_boostedShiftedSrc12Up.err
output = Histo_2000_TTToSemiLeptonic_boostedShiftedSrc12Up.out
log = Histo_2000_TTToSemiLeptonic_boostedShiftedSrc12Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Extended_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = Histo_2000_TTToSemiLeptonic_boostedShiftedSrc12Up.root
queue
