universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Extended_JES.C(\"TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc26Down.root\",\"TTTo2L2Nu\",\"boostedShiftedSrc26Down\",\"2016_postVFP\",2000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_postVFP/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc26Down.root
error = Histo_2000_TTTo2L2Nu_boostedShiftedSrc26Down.err
output = Histo_2000_TTTo2L2Nu_boostedShiftedSrc26Down.out
log = Histo_2000_TTTo2L2Nu_boostedShiftedSrc26Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Extended_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = Histo_2000_TTTo2L2Nu_boostedShiftedSrc26Down.root
queue
