universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Extended_JES.C(\"TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc1Down.root\",\"TTTo2L2Nu\",\"boostedShiftedSrc1Down\",\"2016_postVFP\",1200) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_postVFP/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc1Down.root
error = Histo_1200_TTTo2L2Nu_boostedShiftedSrc1Down.err
output = Histo_1200_TTTo2L2Nu_boostedShiftedSrc1Down.out
log = Histo_1200_TTTo2L2Nu_boostedShiftedSrc1Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Extended_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = Histo_1200_TTTo2L2Nu_boostedShiftedSrc1Down.root
queue
