universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Reduced_JES.C(\"TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc17Up.root\",\"TTToHadronic\",\"boostedShiftedSrc17Up\",\"2017\",1600) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2017/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc17Up.root
error = HistoReduced_1600_TTToHadronic_boostedShiftedSrc17Up.err
output = HistoReduced_1600_TTToHadronic_boostedShiftedSrc17Up.out
log = HistoReduced_1600_TTToHadronic_boostedShiftedSrc17Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_1600_TTToHadronic_boostedShiftedSrc17Up.root
queue
