universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Extended_JES.C(\"TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc2Down.root\",\"TTToHadronic\",\"boostedShiftedSrc2Down\",\"2016_postVFP\",1400) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_postVFP/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc2Down.root
error = Histo_1400_TTToHadronic_boostedShiftedSrc2Down.err
output = Histo_1400_TTToHadronic_boostedShiftedSrc2Down.out
log = Histo_1400_TTToHadronic_boostedShiftedSrc2Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Extended_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = Histo_1400_TTToHadronic_boostedShiftedSrc2Down.root
queue
