universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Extended_JES.C(\"TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc8Down.root\",\"TTToHadronic\",\"boostedShiftedSrc8Down\",\"2016_preVFP\",1200) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_preVFP/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc8Down.root
error = Histo_1200_TTToHadronic_boostedShiftedSrc8Down.err
output = Histo_1200_TTToHadronic_boostedShiftedSrc8Down.out
log = Histo_1200_TTToHadronic_boostedShiftedSrc8Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Extended_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = Histo_1200_TTToHadronic_boostedShiftedSrc8Down.root
queue
