universe = vanilla
executable = submit_.sh
arguments = -l -b -q ResponseMatrices_JES.C(\"/eos/cms/store/user/ipapakri/ttbar/MC/Signal/2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc18Down.root\",\"TTToSemiLeptonic\",\"boostedShiftedSrc18Down\",\"2018\",1000)
error = ResponsesEfficiency_TTToSemiLeptonic_boostedShiftedSrc18Down.err
output = ResponsesEfficiency_TTToSemiLeptonic_boostedShiftedSrc18Down.out
log = ResponsesEfficiency_TTToSemiLeptonic_boostedShiftedSrc18Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = ResponseMatrices_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = ResponsesEfficiency_TTToSemiLeptonic_boostedShiftedSrc18Down.root
queue
