universe = vanilla
executable = submit_.sh
arguments = -l -b -q ResponseMatrices_JES.C(\"/eos/cms/store/user/ipapakri/ttbar/MC/Signal/2018/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc23Down.root\",\"TTToHadronic\",\"boostedShiftedSrc23Down\",\"2018\",1000)
error = ResponsesEfficiency_TTToHadronic_boostedShiftedSrc23Down.err
output = ResponsesEfficiency_TTToHadronic_boostedShiftedSrc23Down.out
log = ResponsesEfficiency_TTToHadronic_boostedShiftedSrc23Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = ResponseMatrices_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = ResponsesEfficiency_TTToHadronic_boostedShiftedSrc23Down.root
queue
