universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Extended_JES.C(\"TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedDown.root\",\"TTToHadronic\",\"boostedShiftedDown\",\"2017\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2017/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedDown.root
error = Histo_1000_TTToHadronic_boostedShiftedDown.err
output = Histo_1000_TTToHadronic_boostedShiftedDown.out
log = Histo_1000_TTToHadronic_boostedShiftedDown.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Extended_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = Histo_1000_TTToHadronic_boostedShiftedDown.root
queue
