universe = vanilla
executable = submit_.sh
arguments = -l -b -q ResponseMatrices_JES.C(\"TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc3Up.root\",\"TTToHadronic\",\"boostedShiftedSrc3Up\",\"2017\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2017/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc3Up.root
error = ResponsesEfficiency_TTToHadronic_boostedShiftedSrc3Up.err
output = ResponsesEfficiency_TTToHadronic_boostedShiftedSrc3Up.out
log = ResponsesEfficiency_TTToHadronic_boostedShiftedSrc3Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = ResponseMatrices_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = ResponsesEfficiency_TTToHadronic_boostedShiftedSrc3Up.root
queue
