universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Reduced_JES.C(\"TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc11Up.root\",\"TTToSemiLeptonic\",\"boostedShiftedSrc11Up\",\"2016_postVFP\",1600) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_postVFP/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc11Up.root
error = HistoReduced_1600_TTToSemiLeptonic_boostedShiftedSrc11Up.err
output = HistoReduced_1600_TTToSemiLeptonic_boostedShiftedSrc11Up.out
log = HistoReduced_1600_TTToSemiLeptonic_boostedShiftedSrc11Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_1600_TTToSemiLeptonic_boostedShiftedSrc11Up.root
queue
