universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Extended_JES.C(\"TTToHadronic_mtop178p5_TuneCP5_13TeV-powheg-pythia8.root\",\"TTToHadronic\",\"13TeV-powheg-pythia8\",\"2018\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2018/TTToHadronic_mtop178p5_TuneCP5_13TeV-powheg-pythia8.root
error = Histo_1000_TTToHadronic_13TeV-powheg-pythia8.err
output = Histo_1000_TTToHadronic_13TeV-powheg-pythia8.out
log = Histo_1000_TTToHadronic_13TeV-powheg-pythia8.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Extended_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = Histo_1000_TTToHadronic_13TeV-powheg-pythia8.root
queue
