universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Reduced_JES.C(\"TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc23Down.root\",\"TTToSemiLeptonic\",\"boostedShiftedSrc23Down\",\"2016_preVFP\",1200) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_preVFP/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc23Down.root
error = HistoReduced_1200_TTToSemiLeptonic_boostedShiftedSrc23Down.err
output = HistoReduced_1200_TTToSemiLeptonic_boostedShiftedSrc23Down.out
log = HistoReduced_1200_TTToSemiLeptonic_boostedShiftedSrc23Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_1200_TTToSemiLeptonic_boostedShiftedSrc23Down.root
queue
