universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Reduced_JES.C(\"TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc1Down.root\",\"TTToSemiLeptonic\",\"boostedShiftedSrc1Down\",\"2016_postVFP\",1400) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_postVFP/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc1Down.root
error = HistoReduced_1400_TTToSemiLeptonic_boostedShiftedSrc1Down.err
output = HistoReduced_1400_TTToSemiLeptonic_boostedShiftedSrc1Down.out
log = HistoReduced_1400_TTToSemiLeptonic_boostedShiftedSrc1Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_1400_TTToSemiLeptonic_boostedShiftedSrc1Down.root
queue
