universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Reduced_JES.C(\"TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc5Up.root\",\"TTToHadronic\",\"boostedShiftedSrc5Up\",\"2016_preVFP\",2000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_preVFP/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc5Up.root
error = HistoReduced_2000_TTToHadronic_boostedShiftedSrc5Up.err
output = HistoReduced_2000_TTToHadronic_boostedShiftedSrc5Up.out
log = HistoReduced_2000_TTToHadronic_boostedShiftedSrc5Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_2000_TTToHadronic_boostedShiftedSrc5Up.root
queue
