universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Reduced_JES.C(\"TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc4Down.root\",\"TTToHadronic\",\"boostedShiftedSrc4Down\",\"2016_preVFP\",1600) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_preVFP/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc4Down.root
error = HistoReduced_1600_TTToHadronic_boostedShiftedSrc4Down.err
output = HistoReduced_1600_TTToHadronic_boostedShiftedSrc4Down.out
log = HistoReduced_1600_TTToHadronic_boostedShiftedSrc4Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_1600_TTToHadronic_boostedShiftedSrc4Down.root
queue
