universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Reduced_JES.C(\"TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc7Down.root\",\"TTToSemiLeptonic\",\"boostedShiftedSrc7Down\",\"2016_postVFP\",2000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_postVFP/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc7Down.root
error = HistoReduced_2000_TTToSemiLeptonic_boostedShiftedSrc7Down.err
output = HistoReduced_2000_TTToSemiLeptonic_boostedShiftedSrc7Down.out
log = HistoReduced_2000_TTToSemiLeptonic_boostedShiftedSrc7Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_2000_TTToSemiLeptonic_boostedShiftedSrc7Down.root
queue
