universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Reduced_JES.C(\"TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc15Up.root\",\"TTTo2L2Nu\",\"boostedShiftedSrc15Up\",\"2016_preVFP\",1400) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_preVFP/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc15Up.root
error = HistoReduced_1400_TTTo2L2Nu_boostedShiftedSrc15Up.err
output = HistoReduced_1400_TTTo2L2Nu_boostedShiftedSrc15Up.out
log = HistoReduced_1400_TTTo2L2Nu_boostedShiftedSrc15Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_1400_TTTo2L2Nu_boostedShiftedSrc15Up.root
queue
