universe = vanilla
executable = submit_.sh
arguments = -l -b -q FillHistograms_Reduced_JES.C(\"TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc24Up.root\",\"TTToSemiLeptonic\",\"boostedShiftedSrc24Up\",\"2018\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc24Up.root
error = HistoReduced_1000_TTToSemiLeptonic_boostedShiftedSrc24Up.err
output = HistoReduced_1000_TTToSemiLeptonic_boostedShiftedSrc24Up.out
log = HistoReduced_1000_TTToSemiLeptonic_boostedShiftedSrc24Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = FillHistograms_Reduced_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = HistoReduced_1000_TTToSemiLeptonic_boostedShiftedSrc24Up.root
queue
