universe = vanilla
executable = submit_.sh
arguments = -l -b -q ResponseMatrices_JES.C(\"TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc5Up.root\",\"TTToSemiLeptonic\",\"boostedShiftedSrc5Up\",\"2018\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc5Up.root
error = ResponsesEfficiency_TTToSemiLeptonic_boostedShiftedSrc5Up.err
output = ResponsesEfficiency_TTToSemiLeptonic_boostedShiftedSrc5Up.out
log = ResponsesEfficiency_TTToSemiLeptonic_boostedShiftedSrc5Up.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = ResponseMatrices_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = ResponsesEfficiency_TTToSemiLeptonic_boostedShiftedSrc5Up.root
queue
