#define M_W (msi.M_W)
#define M_Z (msi.M_Z)
#define M_H (msi.M_H)
#define M_t (msi.M_t)
#define M_b (msi.M_b)
#define M_c (msi.M_c)
#define M_s (msi.M_s)
#define M_u (msi.M_u)
#define M_d (msi.M_d)
#define M_e (msi.M_e)
#define M_mu (msi.M_mu)
#define M_tau (msi.M_tau)
#define M_ve (msi.M_ve)
#define M_vm (msi.M_vm)
#define M_vt (msi.M_vt)

#define M2_W (msi.M2_W)
#define M2_Z (msi.M2_Z)
#define M2_H (msi.M2_H)
#define M2_t (msi.M2_t)
#define M2_b (msi.M2_b)
#define M2_c (msi.M2_c)
#define M2_s (msi.M2_s)
#define M2_u (msi.M2_u)
#define M2_d (msi.M2_d)
#define M2_e (msi.M2_e)
#define M2_mu (msi.M2_mu)
#define M2_tau (msi.M2_tau)
#define M2_ve (msi.M2_ve)
#define M2_vm (msi.M2_vm)
#define M2_vt (msi.M2_vt)

#define Gamma_W (msi.Gamma_W)
#define Gamma_Z (msi.Gamma_Z)
#define Gamma_H (msi.Gamma_H)
#define Gamma_t (msi.Gamma_t)
#define Gamma_b (msi.Gamma_b)
#define Gamma_c (msi.Gamma_c)

#define map_Gamma_W (msi.map_Gamma_W)
#define map_Gamma_Z (msi.map_Gamma_Z)
#define map_Gamma_H (msi.map_Gamma_H)
#define map_Gamma_t (msi.map_Gamma_t)
#define map_Gamma_b (msi.map_Gamma_b)
#define map_Gamma_c (msi.map_Gamma_c)

#define reg_Gamma_W (msi.reg_Gamma_W)
#define reg_Gamma_Z (msi.reg_Gamma_Z)
#define reg_Gamma_H (msi.reg_Gamma_H)
#define reg_Gamma_t (msi.reg_Gamma_t)
#define reg_Gamma_b (msi.reg_Gamma_b)
#define reg_Gamma_c (msi.reg_Gamma_c)

#define cM_W (msi.cM_W)
#define cM_Z (msi.cM_Z)
#define cM_H (msi.cM_H)
#define cM_t (msi.cM_t)
#define cM_b (msi.cM_b)
#define cM_c (msi.cM_c)

#define cM2_W (msi.cM2_W)
#define cM2_Z (msi.cM2_Z)
#define cM2_H (msi.cM2_H)
#define cM2_t (msi.cM2_t)
#define cM2_b (msi.cM2_b)
#define cM2_c (msi.cM2_c)

#define G_F (msi.G_F)

#define Gamma_Wlv (msi.Gamma_Wlv)
#define Gamma_Wud (msi.Gamma_Wud)
#define Gamma_Zll (msi.Gamma_Zll)
#define Gamma_Zvv (msi.Gamma_Zvv)
#define Gamma_Zdd (msi.Gamma_Zdd)
#define Gamma_Zuu (msi.Gamma_Zuu)
#define Gamma_tWb (msi.Gamma_tWb)

#define BR_Wlv (msi.BR_Wlv)
#define BR_Wud (msi.BR_Wud)
#define BR_Zll (msi.BR_Zll)
#define BR_Zvv (msi.BR_Zvv)
#define BR_Zdd (msi.BR_Zdd)
#define BR_Zuu (msi.BR_Zuu)
#define BR_tWb (msi.BR_tWb)

#define alpha_s (msi.alpha_s)
#define s (msi.s)

#define alpha_e (msi.alpha_e)
#define e (msi.e)

#define cos_w (msi.cos_w)
#define cos2_w (msi.cos2_w)
#define sin2_w (msi.sin2_w)
#define sin_w (msi.sin_w)

#define ccos_w (msi.ccos_w)
#define ccos2_w (msi.ccos2_w)
#define csin2_w (msi.csin2_w)
#define csin_w (msi.csin_w)

#define theta_c (msi.theta_c)

#define e_pow (msi.e_pow)
#define V_ckm (msi.V_ckm)
#define M (msi.M)
#define M2 (msi.M2)
#define Gamma (msi.Gamma)
#define cM (msi.cM)
#define cM2 (msi.cM2)
#define map_Gamma (msi.map_Gamma)
#define reg_Gamma (msi.reg_Gamma)



#define Cplus_Zuu (msi.Cplus_Zuu)
#define Cplus_Zdd (msi.Cplus_Zdd)
#define Cminus_Zuu (msi.Cminus_Zuu)
#define Cminus_Zdd (msi.Cminus_Zdd)
#define Cplus_Znn (msi.Cplus_Znn)
#define Cplus_Zee (msi.Cplus_Zee)
#define Cminus_Znn (msi.Cminus_Znn)
#define Cminus_Zee (msi.Cminus_Zee)
#define C_ZWminusWplus (msi.C_ZWminusWplus)

#define Cplus_Auu (msi.Cplus_Auu)
#define Cplus_Add (msi.Cplus_Add)
#define Cminus_Auu (msi.Cminus_Auu)
#define Cminus_Add (msi.Cminus_Add)
#define Cplus_Ann (msi.Cplus_Ann)
#define Cplus_Aee (msi.Cplus_Aee)
#define Cminus_Ann (msi.Cminus_Ann)
#define Cminus_Aee (msi.Cminus_Aee)
#define C_AWminusWplus (msi.C_AWminusWplus)

#define Cminus_W (msi.Cminus_W)

#define cCplus_Zuu (msi.cCplus_Zuu)
#define cCplus_Zdd (msi.cCplus_Zdd)
#define cCminus_Zuu (msi.cCminus_Zuu)
#define cCminus_Zdd (msi.cCminus_Zdd)
#define cCplus_Znn (msi.cCplus_Znn)
#define cCplus_Zee (msi.cCplus_Zee)
#define cCminus_Znn (msi.cCminus_Znn)
#define cCminus_Zee (msi.cCminus_Zee)
#define cC_ZWminusWplus (msi.cC_ZWminusWplus)

#define cCplus_Auu (msi.Cplus_Auu)
#define cCplus_Add (msi.Cplus_Add)
#define cCminus_Auu (msi.Cminus_Auu)
#define cCminus_Add (msi.Cminus_Add)
#define cCplus_Ann (msi.Cplus_Ann)
#define cCplus_Aee (msi.Cplus_Aee)
#define cCminus_Ann (msi.Cminus_Ann)
#define cCminus_Aee (msi.Cminus_Aee)
#define cC_AWminusWplus (msi.C_AWminusWplus)

#define cCminus_W (msi.cCminus_W)
