universe = vanilla
executable = submit_.sh
arguments = -l -b -q ResponseMatrices_JES.C(\"TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc17Down.root\",\"TTToSemiLeptonic\",\"boostedShiftedSrc17Down\",\"2016_preVFP\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_preVFP/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_boostedShiftedSrc17Down.root
error = ResponsesEfficiency_TTToSemiLeptonic_boostedShiftedSrc17Down.err
output = ResponsesEfficiency_TTToSemiLeptonic_boostedShiftedSrc17Down.out
log = ResponsesEfficiency_TTToSemiLeptonic_boostedShiftedSrc17Down.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = ResponseMatrices_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = ResponsesEfficiency_TTToSemiLeptonic_boostedShiftedSrc17Down.root
queue
