universe = vanilla
executable = submit_.sh
arguments = -l -b -q ResponseMatrices_JES.C(\"TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedUp.root\",\"TTTo2L2Nu\",\"boostedShiftedUp\",\"2016_preVFP\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_preVFP/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_boostedShiftedUp.root
error = ResponsesEfficiency_TTTo2L2Nu_boostedShiftedUp.err
output = ResponsesEfficiency_TTTo2L2Nu_boostedShiftedUp.out
log = ResponsesEfficiency_TTTo2L2Nu_boostedShiftedUp.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = ResponseMatrices_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = ResponsesEfficiency_TTTo2L2Nu_boostedShiftedUp.root
queue
