universe = vanilla
executable = submit_.sh
arguments = -l -b -q ResponseMatrices_JES.C(\"TTToSemiLeptonic_mtop178p5_TuneCP5_13TeV-powheg-pythia8.root\",\"TTToSemiLeptonic\",\"13TeV-powheg-pythia8\",\"2016_preVFP\",1000) root://grid02.physics.uoi.gr:1094//store/user/ipapakri/ttbar/MC/Signal/2016_preVFP/TTToSemiLeptonic_mtop178p5_TuneCP5_13TeV-powheg-pythia8.root
error = ResponsesEfficiency_TTToSemiLeptonic_13TeV-powheg-pythia8.err
output = ResponsesEfficiency_TTToSemiLeptonic_13TeV-powheg-pythia8.out
log = ResponsesEfficiency_TTToSemiLeptonic_13TeV-powheg-pythia8.log
+JobFlavour = "testmatch"
+AccountingGroup = "group_u_CMS.u_zh.users"

should_transfer_files = yes
transfer_input_files = ResponseMatrices_JES.C, TemplateConstants.h
when_to_transfer_output = ON_EXIT
transfer_output_files = ResponsesEfficiency_TTToSemiLeptonic_13TeV-powheg-pythia8.root
queue
